import { Property, Lease, InventoryItem, Expense, MarketComp, VaultDocument, PortfolioAnalytics, UserProfile } from '../types';

export const initialUser: UserProfile = {
  id: 'user_demo_landlord',
  email: 'admin@resr.sk',
  name: 'Správca',
  role: 'landlord',
};

export const initialProperties: Property[] = [
  {
    id: 'prop_1789904376801',
    userId: 'user_demo_landlord',
    name: 'PRIKLAD Arboria',
    unitNumber: '100',
    address: 'Veterna 44',
    postalCode: '',
    city: 'Trnava',
    neighborhood: '',
    sizeSqm: 62,
    floor: 4,
    bedrooms: 2,
    bathrooms: 1,
    rentAmount: 750,
    baseRent: 600,
    utilitiesAmount: 150,
    status: 'occupied',
    activeLeaseId: 'lease_1789922265004',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
    hasCellar: true,
    cellarAreaSqm: 10,
    cellarNumber: 'k',
    hasParking: true,
    parkingSpotNumber: '',
    hasAC: true,
    hasBalcony: true,
    furnishingStatus: 'furnished',
    propertyType: 'flat',
    notes: '',
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
    ],
    createdAt: '2026-09-20T11:39:35.909Z',
    tenantName: 'asa',
    tenantEmail: '',
    tenantPhone: '',
    leaseEndDate: '2027-09-20',
  },
  {
    id: 'prop_ovruc_deluxe',
    userId: 'user_demo_landlord',
    name: 'Apartmán Deluxe (Aplend Ovruč)',
    unitNumber: '100',
    address: 'K Vodopádom 4060',
    postalCode: '059 85',
    city: 'Štrbské Pleso',
    neighborhood: 'Vysoké Tatry',
    sizeSqm: 48,
    bedrooms: 2,
    bathrooms: 1,
    rentAmount: 1450,
    baseRent: 1450,
    utilitiesAmount: 0,
    status: 'occupied',
    activeLeaseId: 'lease_ovruc_operator',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    ],
    hasCellar: false,
    hasParking: true,
    hasAC: false,
    hasBalcony: true,
    furnishingStatus: 'furnished',
    propertyType: 'apartment',
    notes: 'Hotelový apartmán v komplexe Aplend Ovruč na Štrbskom Plese. Automatické sledovanie cien na Booking.com.',
    createdAt: '2026-09-21T17:29:52.853Z',
    tenantName: 'APLEND Hotel Services s.r.o.',
    tenantEmail: 'tatry@aplend.com',
    tenantPhone: '+421 904 744 000',
    leaseEndDate: '2027-12-31',
  },
];

export const initialLeases: Lease[] = [
  {
    id: 'lease_1789922265004',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1789904376801',
    tenantName: 'asa',
    tenantEmail: '',
    tenantPhone: '',
    rentAmount: 750,
    baseRent: 600,
    utilitiesAmount: 150,
    depositAmount: 1500,
    startDate: '2026-09-20',
    endDate: '2027-09-20',
    status: 'active',
    propertyName: 'PRIKLAD Arboria',
    propertyUnit: '100',
  },
  {
    id: 'lease_ovruc_operator',
    userId: 'user_demo_landlord',
    propertyId: 'prop_ovruc_deluxe',
    tenantName: 'APLEND Hotel Services s.r.o.',
    tenantEmail: 'tatry@aplend.com',
    tenantPhone: '+421 904 744 000',
    leaseType: 'hotel_operator',
    operatorCompany: 'APLEND Ovruč',
    rentAmount: 1450,
    baseRent: 1450,
    utilitiesAmount: 0,
    depositAmount: 0,
    startDate: '2025-01-01',
    endDate: '2027-12-31',
    status: 'active',
    propertyName: 'Apartmán Deluxe (Aplend Ovruč)',
    propertyUnit: 'Deluxe',
  },
];

export const initialInventory: InventoryItem[] = [];

export const initialExpenses: Expense[] = [];

export const initialMarketComps: MarketComp[] = [
  {
    id: 'comp_1',
    neighborhood: 'Mitte',
    avgRentPerSqm: 24.8,
    propertyType: 'Apartment',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 4.2,
  },
  {
    id: 'comp_2',
    neighborhood: 'Prenzlauer Berg',
    avgRentPerSqm: 23.5,
    propertyType: 'Loft / Altbau',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 5.1,
  },
  {
    id: 'comp_3',
    neighborhood: 'Neukölln',
    avgRentPerSqm: 21.2,
    propertyType: 'Studio / 2-Room',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 6.8,
  },
  {
    id: 'comp_4',
    neighborhood: 'Charlottenburg',
    avgRentPerSqm: 25.5,
    propertyType: 'Luxury Penthouse',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 3.4,
  },
  {
    id: 'comp_5',
    neighborhood: 'Friedrichshain',
    avgRentPerSqm: 22.9,
    propertyType: 'Modern Flat',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 4.9,
  },
  {
    id: 'comp_6',
    neighborhood: 'Kreuzberg',
    avgRentPerSqm: 23.9,
    propertyType: 'Altbau High Ceilings',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 5.5,
  },
];

export const initialDocuments: VaultDocument[] = [
  {
    id: 'doc_ovruc_inv_1',
    userId: 'user_demo_landlord',
    propertyId: 'prop_ovruc_deluxe',
    leaseId: 'lease_ovruc_operator',
    name: 'Vyúčtovanie a faktúra – August 2026',
    category: 'invoice',
    fileSize: '412 KB',
    uploadDate: '2026-09-05',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Mesačné vyúčtovanie prevádzky a provízie od APLEND Hotel Services s.r.o. (výnos €1,520)',
  },
];
