export const initialProperties = [
  {
    id: 'prop_1',
    userId: 'user_demo_landlord',
    name: 'Riverside Residences',
    unitNumber: 'Apt 4B',
    address: '124 Spreeufer Boulevard',
    postalCode: '10178',
    city: 'Berlin',
    neighborhood: 'Mitte',
    sizeSqm: 78.5,
    bedrooms: 2,
    bathrooms: 1.5,
    rentAmount: 1850,
    status: 'occupied',
    activeLeaseId: 'lease_1',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'prop_2',
    userId: 'user_demo_landlord',
    name: 'Kollwitz Court Loft',
    unitNumber: 'Unit 12',
    address: '45 Kollwitzstrasse',
    postalCode: '10405',
    city: 'Berlin',
    neighborhood: 'Prenzlauer Berg',
    sizeSqm: 92.0,
    bedrooms: 3,
    bathrooms: 2.0,
    rentAmount: 2350,
    status: 'occupied',
    activeLeaseId: 'lease_2',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2024-11-20T10:00:00Z',
  },
  {
    id: 'prop_3',
    userId: 'user_demo_landlord',
    name: 'Canal View Studio',
    unitNumber: 'Studio 2A',
    address: '89 Maybachufer',
    postalCode: '12047',
    city: 'Berlin',
    neighborhood: 'Neukölln',
    sizeSqm: 42.0,
    bedrooms: 1,
    bathrooms: 1.0,
    rentAmount: 980,
    status: 'occupied',
    activeLeaseId: 'lease_3',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'prop_4',
    userId: 'user_demo_landlord',
    name: 'Schiller Garden Suite',
    unitNumber: 'Suite 103',
    address: '14 Schillerpromenade',
    postalCode: '12049',
    city: 'Berlin',
    neighborhood: 'Neukölln',
    sizeSqm: 64.0,
    bedrooms: 2,
    bathrooms: 1.0,
    rentAmount: 1420,
    status: 'vacant',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'prop_5',
    userId: 'user_demo_landlord',
    name: 'Savigny Atelier Penthouse',
    unitNumber: 'PH-1',
    address: '32 Knesebeckstrasse',
    postalCode: '10623',
    city: 'Berlin',
    neighborhood: 'Charlottenburg',
    sizeSqm: 115.0,
    bedrooms: 3,
    bathrooms: 2.5,
    rentAmount: 3100,
    status: 'vacant',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80',
    createdAt: '2024-08-10T10:00:00Z',
  },
];

export const initialLeases = [
  {
    id: 'lease_1',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    tenantName: 'Dr. Maximilian Weber',
    tenantEmail: 'm.weber@charite.de',
    tenantPhone: '+49 171 4920194',
    rentAmount: 1850,
    depositAmount: 5550,
    startDate: '2025-11-01',
    endDate: '2026-10-31',
    status: 'active',
    contractFileName: 'Lease_Agreement_Riverside_4B.pdf',
    contractFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'lease_2',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    tenantName: 'Elena Rostova & Kai Becker',
    tenantEmail: 'elena.rostova@techcorp.io',
    tenantPhone: '+49 176 8820411',
    rentAmount: 2350,
    depositAmount: 7050,
    startDate: '2024-03-01',
    endDate: '2026-12-15',
    status: 'active',
    contractFileName: 'Contract_Kollwitz_Unit12_Signed.pdf',
    contractFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'lease_3',
    userId: 'user_demo_landlord',
    propertyId: 'prop_3',
    tenantName: 'Sophie Laurent',
    tenantEmail: 'sophie.laurent@designstudio.fr',
    tenantPhone: '+49 152 3349018',
    rentAmount: 980,
    depositAmount: 2940,
    startDate: '2025-05-01',
    endDate: '2026-10-15',
    status: 'active',
    contractFileName: 'Tenancy_Maybachufer_2A.pdf',
    contractFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
];

export const initialInventory = [
  {
    id: 'inv_1',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    name: 'Induction Cooktop 80cm',
    category: 'appliance',
    brandModel: 'Siemens iQ700 EX875KYW1E',
    serialNumber: 'SN-SIEM-984210',
    purchaseDate: '2023-04-15',
    warrantyExpiresAt: '2026-11-15',
    lifespanYears: 10,
    cost: 1199,
    notes: 'Under extended 3-year store warranty. Top glass scratch-free.',
  },
  {
    id: 'inv_2',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    name: 'Integrated Dishwasher',
    category: 'appliance',
    brandModel: 'Bosch Serie 6 SMV6ZCX07E',
    serialNumber: 'SN-BOSCH-441029',
    purchaseDate: '2022-08-10',
    warrantyExpiresAt: '2024-08-10',
    lifespanYears: 8,
    cost: 849,
    notes: 'Warranty expired. Regular descaling scheduled.',
  },
  {
    id: 'inv_3',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    name: 'EcoSmart Washing Machine',
    category: 'appliance',
    brandModel: 'Miele TwinDos WWI860',
    serialNumber: 'SN-MIELE-772910',
    purchaseDate: '2024-01-20',
    warrantyExpiresAt: '2027-01-20',
    lifespanYears: 12,
    cost: 1450,
    notes: 'Premium motor with 10-year parts guarantee.',
  },
  {
    id: 'inv_4',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    name: 'French Door Refrigerator',
    category: 'appliance',
    brandModel: 'Liebherr Monolith EKB9471',
    serialNumber: 'SN-LIEB-553198',
    purchaseDate: '2023-09-05',
    warrantyExpiresAt: '2026-10-05',
    lifespanYears: 12,
    cost: 2890,
    notes: 'Dual cooling circuit. Filters replaced May 2026.',
  },
  {
    id: 'inv_5',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    name: 'Designer Modular Sofa',
    category: 'furniture',
    brandModel: 'BoConcept Carmo Velvet',
    serialNumber: 'SOFA-BC-2023',
    purchaseDate: '2023-10-01',
    warrantyExpiresAt: '2028-10-01',
    lifespanYears: 10,
    cost: 3400,
    notes: 'Treated with water-repellent nanofiber coat.',
  },
  {
    id: 'inv_6',
    userId: 'user_demo_landlord',
    propertyId: 'prop_3',
    name: 'Compact Washer-Dryer',
    category: 'appliance',
    brandModel: 'AEG DualSense 7000',
    serialNumber: 'SN-AEG-102943',
    purchaseDate: '2024-06-12',
    warrantyExpiresAt: '2026-10-25',
    lifespanYears: 7,
    cost: 720,
    notes: 'Warranty expiring in < 40 days! Needs pre-expiry inspection.',
  },
  {
    id: 'inv_7',
    userId: 'user_demo_landlord',
    propertyId: 'prop_4',
    name: 'Air Source Heat Pump AC',
    category: 'fixture',
    brandModel: 'Daikin Emura FTXJ35',
    serialNumber: 'SN-DAIK-901823',
    purchaseDate: '2024-02-14',
    warrantyExpiresAt: '2029-02-14',
    lifespanYears: 15,
    cost: 2600,
    notes: 'Smart WiFi thermostat connected. Highest efficiency A+++.',
  },
  {
    id: 'inv_8',
    userId: 'user_demo_landlord',
    propertyId: 'prop_5',
    name: 'Smart Oven & Steamer',
    category: 'appliance',
    brandModel: 'Gaggenau Series 400',
    serialNumber: 'SN-GAG-332910',
    purchaseDate: '2021-03-01',
    warrantyExpiresAt: '2023-03-01',
    lifespanYears: 12,
    cost: 3800,
    notes: 'Requires heating element replacement during current renovation.',
  },
];

export const initialExpenses = [
  {
    id: 'exp_1',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    category: 'repair',
    amount: 185,
    date: '2026-08-14',
    description: 'Kitchen sink siphon leak fix & gasket sealing',
  },
  {
    id: 'exp_2',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    category: 'utility',
    amount: 240,
    date: '2026-08-01',
    description: 'Annual chimney sweep and ventilation inspection',
  },
  {
    id: 'exp_3',
    userId: 'user_demo_landlord',
    propertyId: 'prop_3',
    category: 'tax',
    amount: 410,
    date: '2026-07-15',
    description: 'Quarterly municipal property tax (Grundsteuer)',
  },
  {
    id: 'exp_4',
    userId: 'user_demo_landlord',
    propertyId: 'prop_5',
    category: 'replacement',
    amount: 1250,
    date: '2026-09-02',
    description: 'Parquet floor sanding and ecological hardwax oil refurbishment',
  },
  {
    id: 'exp_5',
    userId: 'user_demo_landlord',
    propertyId: 'prop_5',
    category: 'repair',
    amount: 620,
    date: '2026-09-10',
    description: 'Master bathroom concealed shower cartridge overhaul',
  },
  {
    id: 'exp_6',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    category: 'repair',
    amount: 145,
    date: '2026-06-20',
    description: 'Balcony drain clearing and waterproof membrane touch-up',
  },
];

export const initialMarketComps = [
  {
    id: 'comp_1',
    neighborhood: 'Mitte',
    avgRentPerSqm: 24.8,
    propertyType: 'Apartment',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 4.2,
  },
  {
    id: 'comp_2',
    neighborhood: 'Prenzlauer Berg',
    avgRentPerSqm: 23.5,
    propertyType: 'Loft / Altbau',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 5.1,
  },
  {
    id: 'comp_3',
    neighborhood: 'Neukölln',
    avgRentPerSqm: 21.2,
    propertyType: 'Studio / 2-Room',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 6.8,
  },
  {
    id: 'comp_4',
    neighborhood: 'Charlottenburg',
    avgRentPerSqm: 25.5,
    propertyType: 'Luxury Penthouse',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 3.4,
  },
  {
    id: 'comp_5',
    neighborhood: 'Friedrichshain',
    avgRentPerSqm: 22.9,
    propertyType: 'Modern Flat',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 4.9,
  },
  {
    id: 'comp_6',
    neighborhood: 'Kreuzberg',
    avgRentPerSqm: 23.9,
    propertyType: 'Altbau High Ceilings',
    lastUpdated: '2026-09-01',
    historicalTrendPercent: 5.5,
  },
];

export const initialDocuments = [
  {
    id: 'doc_1',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    leaseId: 'lease_1',
    name: 'Residential Lease Agreement 2025-2026',
    category: 'tenancy',
    fileSize: '2.4 MB',
    uploadDate: '2025-10-28',
    expiryDate: '2026-10-31',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Fully executed bilateral contract with Dr. Maximilian Weber.',
  },
  {
    id: 'doc_2',
    userId: 'user_demo_landlord',
    propertyId: 'prop_1',
    leaseId: 'lease_1',
    name: 'Handover Protocol & Meter Readings',
    category: 'inspection',
    fileSize: '4.1 MB',
    uploadDate: '2025-11-01',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Contains 28 photos of unit condition and initial water/electricity counters.',
  },
  {
    id: 'doc_3',
    userId: 'user_demo_landlord',
    propertyId: 'prop_2',
    leaseId: 'lease_2',
    name: 'Signed Tenancy Agreement - Kollwitz Court',
    category: 'tenancy',
    fileSize: '3.1 MB',
    uploadDate: '2024-02-28',
    expiryDate: '2026-12-15',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Co-signed by Elena Rostova & Kai Becker.',
  },
  {
    id: 'doc_4',
    userId: 'user_demo_landlord',
    propertyId: 'prop_5',
    name: 'Renovation Contractor Invoice & Guarantee',
    category: 'invoice',
    fileSize: '1.2 MB',
    uploadDate: '2026-09-05',
    expiryDate: '2031-09-05',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Includes 5-year workmanship guarantee from Meisterbau GmbH.',
  },
];
